const mongoose = require('mongoose');

const businessSchema = new mongoose.Schema({
  business_name: { type: String, required: true },
  owner: {
    user_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    name: { type: String, required: true },
    email: { type: String, required: true },
  },
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now }
});

// We can create a virtual field for business_id that will be the same as the _id generated by MongoDB
businessSchema.virtual('business_id').get(function() {
  return this._id.toString();
});

module.exports = mongoose.model('Business', businessSchema);
